name: Build and Deploy

on:
  push:
    branches:
      - main  # Runs only when push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t alantomanu/autograde-server:latest .

      - name: Push image to Docker Hub
        run: docker push alantomanu/autograde-server:latest